Fixed broken drawPlaceholder function and length check on strings
aleksandrshoshiashvili/AwesomeTextFieldSwift pull request #9
Opened 2017-05-23 19:52 UTC by AfreX

Switch to character count on strings instead of length check  (swift 3.1)

source : https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/StringsAndCharacters.html#//apple_ref/doc/uid/TP40014097-CH7-ID297

2017-05-23 21:40 UTC, NikoGenn requested changes

2017-05-23 21:40 UTC, NikoGenn commented on AwesomeTextField/Classes/AwesomeTextField.swift
> +
Please, remove trailing whitespaces on blank lines.
The rest looks good to merge

2017-05-23 23:25 UTC, afrex commented
@NikoGenn Done

2017-05-24 07:31 UTC, NikoGenn approved these changes

2017-05-24 07:31 UTC, merged